/**
 * Top Sydney / Greater Sydney & common NSW suburbs for autocomplete (not exhaustive).
 * Postcodes are representative; verify on official sources for conveyancing.
 */
export type NswSuburbSuggestion = { suburb: string; postcode: string };

export const NSW_SUBURB_SUGGESTIONS: readonly NswSuburbSuggestion[] = [
  { suburb: "Abbotsford", postcode: "2046" },
  { suburb: "Allawah", postcode: "2218" },
  { suburb: "Arncliffe", postcode: "2205" },
  { suburb: "Asquith", postcode: "2077" },
  { suburb: "Avalon Beach", postcode: "2107" },
  { suburb: "Balgowlah", postcode: "2093" },
  { suburb: "Bardwell Park", postcode: "2207" },
  { suburb: "Bass Hill", postcode: "2197" },
  { suburb: "Bexley", postcode: "2207" },
  { suburb: "Blakehurst", postcode: "2221" },
  { suburb: "Brookvale", postcode: "2100" },
  { suburb: "Cabarita", postcode: "2137" },
  { suburb: "Campsie", postcode: "2194" },
  { suburb: "Collaroy", postcode: "2097" },
  { suburb: "Concord", postcode: "2137" },
  { suburb: "Concord West", postcode: "2138" },
  { suburb: "Davidson", postcode: "2085" },
  { suburb: "Denistone", postcode: "2114" },
  { suburb: "Dundas", postcode: "2117" },
  { suburb: "Engadine", postcode: "2233" },
  { suburb: "Fairlight", postcode: "2094" },
  { suburb: "Freshwater", postcode: "2096" },
  { suburb: "Hillsdale", postcode: "2036" },
  { suburb: "Hunters Hill", postcode: "2110" },
  { suburb: "Hurstville Grove", postcode: "2220" },
  { suburb: "Illawong", postcode: "2234" },
  { suburb: "Ingleburn", postcode: "2565" },
  { suburb: "Jannali", postcode: "2226" },
  { suburb: "Killara", postcode: "2071" },
  { suburb: "Kingsgrove", postcode: "2208" },
  { suburb: "Kirribilli", postcode: "2061" },
  { suburb: "Lakemba", postcode: "2195" },
  { suburb: "Lavender Bay", postcode: "2060" },
  { suburb: "Lilyfield", postcode: "2040" },
  { suburb: "Lugarno", postcode: "2210" },
  { suburb: "Malabar", postcode: "2036" },
  { suburb: "Manly", postcode: "2095" },
  { suburb: "Manly Vale", postcode: "2093" },
  { suburb: "Menai", postcode: "2234" },
  { suburb: "Mortdale", postcode: "2223" },
  { suburb: "Narrabeen North", postcode: "2101" },
  { suburb: "Narwee", postcode: "2209" },
  { suburb: "Northbridge", postcode: "2063" },
  { suburb: "Oatlands", postcode: "2117" },
  { suburb: "Padstow", postcode: "2211" },
  { suburb: "Putney", postcode: "2112" },
  { suburb: "Ramsgate", postcode: "2217" },
  { suburb: "Riverview", postcode: "2066" },
  { suburb: "Rydalmere", postcode: "2116" },
  { suburb: "Seven Hills", postcode: "2147" },
  { suburb: "South Hurstville", postcode: "2221" },
  { suburb: "Sylvania Waters", postcode: "2224" },
  { suburb: "Wentworthville", postcode: "2145" },
  { suburb: "Wiley Park", postcode: "2195" },
  { suburb: "Windsor", postcode: "2756" },
  { suburb: "Woolooware", postcode: "2230" },
  { suburb: "Alexandria", postcode: "2015" },
  { suburb: "Annandale", postcode: "2038" },
  { suburb: "Artarmon", postcode: "2064" },
  { suburb: "Ashfield", postcode: "2131" },
  { suburb: "Auburn", postcode: "2144" },
  { suburb: "Balmain", postcode: "2041" },
  { suburb: "Banksia", postcode: "2216" },
  { suburb: "Bankstown", postcode: "2200" },
  { suburb: "Baulkham Hills", postcode: "2153" },
  { suburb: "Beacon Hill", postcode: "2100" },
  { suburb: "Beaconsfield", postcode: "2015" },
  { suburb: "Bellevue Hill", postcode: "2023" },
  { suburb: "Berala", postcode: "2141" },
  { suburb: "Beverly Hills", postcode: "2209" },
  { suburb: "Blacktown", postcode: "2148" },
  { suburb: "Bondi", postcode: "2026" },
  { suburb: "Bondi Beach", postcode: "2026" },
  { suburb: "Bondi Junction", postcode: "2022" },
  { suburb: "Botany", postcode: "2019" },
  { suburb: "Brighton-Le-Sands", postcode: "2216" },
  { suburb: "Bronte", postcode: "2024" },
  { suburb: "Burwood", postcode: "2134" },
  { suburb: "Cabramatta", postcode: "2166" },
  { suburb: "Cammeray", postcode: "2062" },
  { suburb: "Campbelltown", postcode: "2560" },
  { suburb: "Camperdown", postcode: "2050" },
  { suburb: "Canada Bay", postcode: "2046" },
  { suburb: "Canterbury", postcode: "2193" },
  { suburb: "Caringbah", postcode: "2229" },
  { suburb: "Carlingford", postcode: "2118" },
  { suburb: "Carlton", postcode: "2218" },
  { suburb: "Castle Hill", postcode: "2154" },
  { suburb: "Castlereagh", postcode: "2749" },
  { suburb: "Chatswood", postcode: "2067" },
  { suburb: "Cherrybrook", postcode: "2126" },
  { suburb: "Chippendale", postcode: "2008" },
  { suburb: "Chullora", postcode: "2190" },
  { suburb: "Clifton Gardens", postcode: "2088" },
  { suburb: "Clovelly", postcode: "2031" },
  { suburb: "Coogee", postcode: "2034" },
  { suburb: "Cremorne", postcode: "2090" },
  { suburb: "Cronulla", postcode: "2230" },
  { suburb: "Crows Nest", postcode: "2065" },
  { suburb: "Croydon", postcode: "2132" },
  { suburb: "Croydon Park", postcode: "2133" },
  { suburb: "Darlinghurst", postcode: "2010" },
  { suburb: "Darlington", postcode: "2008" },
  { suburb: "Dee Why", postcode: "2099" },
  { suburb: "Double Bay", postcode: "2028" },
  { suburb: "Dover Heights", postcode: "2030" },
  { suburb: "Drummoyne", postcode: "2047" },
  { suburb: "Dulwich Hill", postcode: "2203" },
  { suburb: "Earlwood", postcode: "2206" },
  { suburb: "Eastgardens", postcode: "2036" },
  { suburb: "Eastlakes", postcode: "2018" },
  { suburb: "Eastwood", postcode: "2122" },
  { suburb: "Edgecliff", postcode: "2027" },
  { suburb: "Elizabeth Bay", postcode: "2011" },
  { suburb: "Enmore", postcode: "2042" },
  { suburb: "Epping", postcode: "2121" },
  { suburb: "Erskineville", postcode: "2043" },
  { suburb: "Eveleigh", postcode: "2015" },
  { suburb: "Fairfield", postcode: "2165" },
  { suburb: "Five Dock", postcode: "2046" },
  { suburb: "Forest Lodge", postcode: "2037" },
  { suburb: "Frenchs Forest", postcode: "2086" },
  { suburb: "Glebe", postcode: "2037" },
  { suburb: "Gladesville", postcode: "2111" },
  { suburb: "Gordon", postcode: "2072" },
  { suburb: "Granville", postcode: "2142" },
  { suburb: "Greenacre", postcode: "2190" },
  { suburb: "Greenwich", postcode: "2065" },
  { suburb: "Guildford", postcode: "2161" },
  { suburb: "Gymea", postcode: "2227" },
  { suburb: "Haberfield", postcode: "2045" },
  { suburb: "Haymarket", postcode: "2000" },
  { suburb: "Homebush", postcode: "2140" },
  { suburb: "Hornsby", postcode: "2077" },
  { suburb: "Hurstville", postcode: "2220" },
  { suburb: "Hurlstone Park", postcode: "2193" },
  { suburb: "Kensington", postcode: "2033" },
  { suburb: "Kingsford", postcode: "2032" },
  { suburb: "Kirrawee", postcode: "2232" },
  { suburb: "Kogarah", postcode: "2217" },
  { suburb: "Kurraba Point", postcode: "2089" },
  { suburb: "La Perouse", postcode: "2036" },
  { suburb: "Lane Cove", postcode: "2066" },
  { suburb: "Leichhardt", postcode: "2040" },
  { suburb: "Lidcombe", postcode: "2141" },
  { suburb: "Lindfield", postcode: "2070" },
  { suburb: "Little Bay", postcode: "2036" },
  { suburb: "Liverpool", postcode: "2170" },
  { suburb: "Longueville", postcode: "2066" },
  { suburb: "Marrickville", postcode: "2204" },
  { suburb: "Maroubra", postcode: "2035" },
  { suburb: "Mascot", postcode: "2020" },
  { suburb: "Matraville", postcode: "2036" },
  { suburb: "McMahons Point", postcode: "2060" },
  { suburb: "Milsons Point", postcode: "2061" },
  { suburb: "Miranda", postcode: "2228" },
  { suburb: "Mona Vale", postcode: "2103" },
  { suburb: "Mosman", postcode: "2088" },
  { suburb: "Mount Druitt", postcode: "2770" },
  { suburb: "Naremburn", postcode: "2065" },
  { suburb: "Narrabeen", postcode: "2101" },
  { suburb: "Neutral Bay", postcode: "2089" },
  { suburb: "Newington", postcode: "2127" },
  { suburb: "Newport", postcode: "2106" },
  { suburb: "Newtown", postcode: "2042" },
  { suburb: "Normanhurst", postcode: "2076" },
  { suburb: "North Bondi", postcode: "2026" },
  { suburb: "North Ryde", postcode: "2113" },
  { suburb: "North Sydney", postcode: "2060" },
  { suburb: "Northmead", postcode: "2152" },
  { suburb: "Oatley", postcode: "2223" },
  { suburb: "Paddington", postcode: "2021" },
  { suburb: "Pagewood", postcode: "2035" },
  { suburb: "Parramatta", postcode: "2150" },
  { suburb: "Peakhurst", postcode: "2210" },
  { suburb: "Pennant Hills", postcode: "2120" },
  { suburb: "Penrith", postcode: "2750" },
  { suburb: "Petersham", postcode: "2049" },
  { suburb: "Point Piper", postcode: "2027" },
  { suburb: "Potts Point", postcode: "2011" },
  { suburb: "Punchbowl", postcode: "2196" },
  { suburb: "Pymble", postcode: "2073" },
  { suburb: "Pyrmont", postcode: "2009" },
  { suburb: "Queenscliff", postcode: "2096" },
  { suburb: "Quakers Hill", postcode: "2763" },
  { suburb: "Randwick", postcode: "2031" },
  { suburb: "Redfern", postcode: "2016" },
  { suburb: "Rhodes", postcode: "2138" },
  { suburb: "Riverwood", postcode: "2210" },
  { suburb: "Rockdale", postcode: "2216" },
  { suburb: "Rodd Point", postcode: "2046" },
  { suburb: "Rose Bay", postcode: "2029" },
  { suburb: "Rosebery", postcode: "2018" },
  { suburb: "Roseville", postcode: "2069" },
  { suburb: "Rozelle", postcode: "2039" },
  { suburb: "Rushcutters Bay", postcode: "2011" },
  { suburb: "Russell Lea", postcode: "2046" },
  { suburb: "Ryde", postcode: "2112" },
  { suburb: "Sandringham", postcode: "2219" },
  { suburb: "Sans Souci", postcode: "2219" },
  { suburb: "Seaforth", postcode: "2092" },
  { suburb: "Silverwater", postcode: "2128" },
  { suburb: "Smithfield", postcode: "2164" },
  { suburb: "St Ives", postcode: "2075" },
  { suburb: "St Leonards", postcode: "2065" },
  { suburb: "St Marys", postcode: "2760" },
  { suburb: "St Peters", postcode: "2044" },
  { suburb: "Stanmore", postcode: "2048" },
  { suburb: "Strathfield", postcode: "2135" },
  { suburb: "Summer Hill", postcode: "2130" },
  { suburb: "Surry Hills", postcode: "2010" },
  { suburb: "Sutherland", postcode: "2232" },
  { suburb: "Sydney", postcode: "2000" },
  { suburb: "Sylvania", postcode: "2224" },
  { suburb: "Tamarama", postcode: "2026" },
  { suburb: "Telopea", postcode: "2117" },
  { suburb: "Terrey Hills", postcode: "2084" },
  { suburb: "The Rocks", postcode: "2000" },
  { suburb: "Toongabbie", postcode: "2146" },
  { suburb: "Turramurra", postcode: "2074" },
  { suburb: "Ultimo", postcode: "2007" },
  { suburb: "Vaucluse", postcode: "2030" },
  { suburb: "Wahroonga", postcode: "2076" },
  { suburb: "Waitara", postcode: "2077" },
  { suburb: "Warriewood", postcode: "2102" },
  { suburb: "Waterloo", postcode: "2017" },
  { suburb: "Watsons Bay", postcode: "2030" },
  { suburb: "Waverton", postcode: "2060" },
  { suburb: "Wentworth Point", postcode: "2127" },
  { suburb: "Westmead", postcode: "2145" },
  { suburb: "West Ryde", postcode: "2114" },
  { suburb: "Willoughby", postcode: "2068" },
  { suburb: "Wolli Creek", postcode: "2205" },
  { suburb: "Wollstonecraft", postcode: "2065" },
  { suburb: "Woollahra", postcode: "2025" },
  { suburb: "Woolloomooloo", postcode: "2011" },
  { suburb: "Woronora", postcode: "2232" },
  { suburb: "Yagoona", postcode: "2199" },
  { suburb: "Yennora", postcode: "2161" },
  { suburb: "Zetland", postcode: "2017" },
  { suburb: "Albury", postcode: "2640" },
  { suburb: "Armidale", postcode: "2350" },
  { suburb: "Ballina", postcode: "2478" },
  { suburb: "Batemans Bay", postcode: "2536" },
  { suburb: "Bathurst", postcode: "2795" },
  { suburb: "Bowral", postcode: "2576" },
  { suburb: "Broken Hill", postcode: "2880" },
  { suburb: "Byron Bay", postcode: "2481" },
  { suburb: "Cessnock", postcode: "2325" },
  { suburb: "Coffs Harbour", postcode: "2450" },
  { suburb: "Dubbo", postcode: "2830" },
  { suburb: "Forster", postcode: "2428" },
  { suburb: "Gosford", postcode: "2250" },
  { suburb: "Goulburn", postcode: "2580" },
  { suburb: "Grafton", postcode: "2460" },
  { suburb: "Griffith", postcode: "2680" },
  { suburb: "Katoomba", postcode: "2780" },
  { suburb: "Kiama", postcode: "2533" },
  { suburb: "Lismore", postcode: "2480" },
  { suburb: "Lithgow", postcode: "2790" },
  { suburb: "Maitland", postcode: "2320" },
  { suburb: "Muswellbrook", postcode: "2333" },
  { suburb: "Nelson Bay", postcode: "2315" },
  { suburb: "Newcastle", postcode: "2300" },
  { suburb: "Nowra", postcode: "2541" },
  { suburb: "Orange", postcode: "2800" },
  { suburb: "Port Macquarie", postcode: "2444" },
  { suburb: "Singleton", postcode: "2330" },
  { suburb: "Tamworth", postcode: "2340" },
  { suburb: "Taree", postcode: "2430" },
  { suburb: "Tweed Heads", postcode: "2485" },
  { suburb: "Wagga Wagga", postcode: "2650" },
  { suburb: "Wollongong", postcode: "2500" },
  { suburb: "Wyong", postcode: "2259" },
  { suburb: "Young", postcode: "2594" },
] as const;

const COLLATOR = new Intl.Collator("en-AU", { sensitivity: "base" });

export function filterNswSuburbSuggestions(
  query: string,
  limit = 8,
): NswSuburbSuggestion[] {
  const q = query.trim().toLowerCase();
  if (q.length < 3) return [];
  const matches: NswSuburbSuggestion[] = [];
  for (const row of NSW_SUBURB_SUGGESTIONS) {
    const name = row.suburb.toLowerCase();
    if (name.includes(q) || row.postcode.includes(q)) {
      matches.push(row);
    }
    if (matches.length >= 80) break;
  }
  matches.sort((a, b) =>
    COLLATOR.compare(a.suburb, b.suburb),
  );
  return matches.slice(0, limit);
}
